# Generated by Django 3.2.6 on 2021-11-01 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accented_Sentence', models.TextField()),
                ('Accentless_Sentence', models.TextField()),
                ('Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Leave_Feedback', models.CharField(blank=True, choices=[('unsatisfied', 'unsatisfied'), ('neutral', 'neutral'), ('satisfied', 'satisfied')], max_length=100, null=True)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
